import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import logo from "../assets/eth.png";
// Layout for the application at large.
// Pass in children to get the same layout across multiple pages

const Layout = ({ children, title = "Crypt", image }) => {
  return (
    <div className="layout">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Link href="/" passHref>
          <a>
            {image ? (
              <img src={image} alt="logo" className="layout-logo" />
            ) : (
              <Image className="logo" src={logo} alt="logo"/>
            )}
          </a>
        </Link>
      </header>
      <main>{children}</main>
    </div>
  );
};

export default Layout;
